# Generated by Django 3.2.7 on 2021-12-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_singerlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='best_color',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
