# Generated by Django 3.2.7 on 2021-12-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_singer_best_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='best_color',
            field=models.CharField(max_length=18),
        ),
    ]
